title: Yun Ho
logo: /assets/img/profile-picture-oval.png
description: PhD Student, University of Chicago
# show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://scholar.google.com/citations?user=Rv2Z0EoAAAAJ&hl=en
  another_url: google scholar
